# This file is for Google cloud deployment
FROM python:3.11

WORKDIR /app

# copy requirements from root
COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# copy backend code
COPY . .

EXPOSE 8080

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]